Vagrant.configure("2") do |config|

  # Setting up the Ubuntu VM
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    ubuntu.vm.boot_timeout = 300 
    
    ubuntu.vm.synced_folder "./../", "/home/vagrant/project"
    ubuntu.vm.provision "shell", path: "VagrantScripts/setup-ubuntu.sh"
  end

 # Setting up the Windows VM
  config.vm.define "windows" do |windows|
    windows.vm.box = "gusztavvargadr/windows-10"
    windows.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    windows.vm.boot_timeout = 300 

    windows.vm.synced_folder "./../", "C:/vagrant/project"
    windows.vm.provision "shell", path: "VagrantScripts/setup-windows.ps1"
  end

  # Setting up the macOS VM
  config.vm.define "macos" do |macos|
    macos.vm.box = "jhcook/macos-sierra"
    macos.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    macos.vm.boot_timeout = 300 

    macos.vm.synced_folder "./../", "/Users/vagrant/project"
    macos.vm.provision "shell", path: "VagrantScripts/setup-macos.sh"
  end

end