Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.boot_timeout = 300 
  
  
  config.vm.synced_folder "../", "/home/vagrant/project"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y

    sudo apt-get install -y wget

    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo apt-get update
    sudo apt-get install -y dotnet-sdk-8.0

    cd /home/vagrant/project/Lab5/Lab5

    dotnet restore
    dotnet build
    dotnet run --urls "http://0.0.0.0:5000"
  SHELL

  config.vm.network "forwarded_port", guest: 5000, host: 5555
end
