version: "3.7"

services:
  db_mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123!
    ports:
      - "1430:1433"
    networks:
      - db-network
    restart: always

  db_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5430:5432"
    networks:
      - db-network
    restart: always

networks:
  db-network:
    driver: bridge
